<a href="https://colab.research.google.com/github/revy1817/Data_Science-Numpy-Matplotlib-Scikit-learn-/blob/less2/less2_repeat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random
from matplotlib import pyplot as plt


# **Задание №1**


---


Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [ ]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


# **Задание №2**


---
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [ ]:
mas1 = np.random.choice(a, (2, random.randrange(2, 8)))
mas2 = np.random.choice(a, (2, random.randrange(2, 8)))
mas3 = np.random.choice(a, (2, random.randrange(2, 8)))
mas4 = np.random.choice(a, (2, random.randrange(2, 8)))
mas5 = np.random.choice(a, (2, random.randrange(2, 8)))

# **Задание №3**


---
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк)



In [ ]:
mas6 = a.reshape(-1, 3)
mas7 = a.reshape(-1, 2)
mas8 = a.reshape(2, -1)
mas9 = a.reshape(3, -1)
mas10 = a.reshape(4, -1)

# **Задание №4**



Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


---

## **Ответ:**
Нет, так как массив Numpy будет включать в себя другие массивы



```
# Выбран кодовый формат
```

# **Задание №5**


---

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [ ]:
mas11 = np.random.randn(3, 4)
print(mas11)

[[-1.60158511e+00  6.58227149e-01 -6.69840502e-01 -1.01808722e+00]
 [ 1.37788066e-03 -1.18187857e+00 -7.72086367e-01  1.30043687e+00]
 [-1.08120034e+00 -4.64307445e-01  6.85354852e-01 -4.91909234e-01]]


In [ ]:
mas12 = mas11.flatten()
print(mas12)

[-1.60158511e+00  6.58227149e-01 -6.69840502e-01 -1.01808722e+00
  1.37788066e-03 -1.18187857e+00 -7.72086367e-01  1.30043687e+00
 -1.08120034e+00 -4.64307445e-01  6.85354852e-01 -4.91909234e-01]


# **Задание №6**


---

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [ ]:
a = np.arange(20, 0, -1)
print(a)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


# **Задание №7**


---

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [ ]:
b = np.arange(20, 1, -2)
print(b.reshape(-1, 1))

[[20]
 [18]
 [16]
 [14]
 [12]
 [10]
 [ 8]
 [ 6]
 [ 4]
 [ 2]]


## **Ответ на вопрос:**
Массив а имеет один вложенный массив, массив b имеет внутри себя 10 вложенных массивов [Текст ссылки](https://)

# **Задание №8**


---
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.



In [ ]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
print(v)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


# **Задание №9**


---

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [ ]:
a = np.arange(0, 12)
a = a.reshape(4, 3)
a_t = a.T
b = a.dot(a_t)
print(b)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


## **Ответ на вопрос:**
Матрица B имеет такие же размеры как и исходные матрицы, так как при умножении квадратных матриц резултатом будет квадратная матрица тех же размеров.
Транспонировать матрицу B можно, так как транспонирование это процесс когда 
строки и столбцы матрицы меняются местами, в матрице B соблюдены все условия 
для это операции 

# **Задание №10**


---
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.



In [ ]:
np.random.seed(seed=42)
np.random.randint(1, 50)


39

# **Задание №11**


---
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [ ]:
c = np.random.randint(0, 16, (1, 16))
print(c)

[[ 1  3  8 11 13  1  9  8  9  4  1  3 11 14 11  6]]


# **Задание №12**



---

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [ ]:
c = c.reshape(4, 4)
d = (c * 10) + b
d_det = np.linalg.det(d)
print(d_det)

-131179000.0000003


In [ ]:
d_r = np.linalg.matrix_rank(d)
print(d_r)

4


In [ ]:
d_inv = np.linalg.inv(d)
print(d_inv)

[[-0.01288362  0.0059633   0.0049479  -0.0015815 ]
 [-0.00987109 -0.00748153  0.00457909  0.00498571]
 [ 0.00448502  0.00845151 -0.0201857   0.00701896]
 [ 0.00820863 -0.00444202  0.0127002  -0.00646902]]


# **Задание №13**


---
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.




In [ ]:
ind1 = np.where(d_inv > 0)
d_inv[ind1] = 1
ind2 = np.where(d_inv < 0)
d_inv[ind2] = 0
print(d_inv)

[[0. 1. 1. 0.]
 [0. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [ ]:
e = np.zeros((4, 4))
e = np.where(d_inv, b, c)
print(e)

[[  1  14  23  11]
 [ 13   1  86 122]
 [ 23  86   1 212]
 [ 32  14 212   6]]
